cursor            #81d3df
cursor_text_color #00363c

foreground            #dee4e4
background            #090f10
selection_foreground  #1c3438
selection_background  #b1cbcf
url_color             #b1cbcf

#: black 000000 767676
color0  #000101
color8  #485152
#: red cc0403 f2201f
color1  #ff4c63
color9  #ffe5e8
#: green 19cb00 23fd00
color2  #4ab870
color10 #b8e3c7
#: yellow cecb00 fffd00
color3  #83ae45
color11 #cadfad
#: blue 0d73cc 1a8fff
color4  #477fff
color12 #e0e9ff
#: magenta cb1ed1 fd28ff
color5  #e55ac3
color13 #fadef3
#: cyan 0dcdcd 14ffff
color6  #31b5cc
color14 #abe1eb
#: white dddddd ffffff
color7  #bfc8ca
color15 #dee4e4

mark1_foreground #001f23
mark1_background #9df0fc
mark2_foreground #051f22
mark2_background #cde7ec
mark3_foreground #0d1b37
mark3_background #d9e2ff

active_tab_foreground #00363c
active_tab_background #81d3df
inactive_tab_foreground #9df0fc
inactive_tab_background #004f57

active_border_color #81d3df
inactive_border_color #00363c
# bell_border_color #ff5a00