cursor            #ffb692
cursor_text_color #542103

foreground            #f0dfd8
background            #140c09
selection_foreground  #432a1e
selection_background  #e6beac
url_color             #e6beac

#: black 000000 767676
color0  #030202
color8  #5a4b44
#: red cc0403 f2201f
color1  #ff6639
color9  #ffdcd2
#: green 19cb00 23fd00
color2  #85ad44
color10 #cbdeac
#: yellow cecb00 fffd00
color3  #b09c31
color11 #e2d798
#: blue 0d73cc 1a8fff
color4  #7958ff
color12 #f4f1ff
#: magenta cb1ed1 fd28ff
color5  #ff4c6a
color13 #ffe5e9
#: cyan 0dcdcd 14ffff
color6  #3bb3b5
color14 #a7e1e2
#: white dddddd ffffff
color7  #d7c2b9
color15 #f0dfd8

mark1_foreground #341100
mark1_background #ffdbcb
mark2_foreground #2c160b
mark2_background #ffdbcb
mark3_foreground #1f1c00
mark3_background #ece4aa

active_tab_foreground #542103
active_tab_background #ffb692
inactive_tab_foreground #ffdbcb
inactive_tab_background #703716

active_border_color #ffb692
inactive_border_color #542103
# bell_border_color #ff5a00