#################
### AUTOSTART ###
#################

source = ~/.config/hypr/hyprland/variables.conf

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar & awww-daemon
exec-once = systemctl --user start hyprpolkitagent
#exec-once = systemctl --user start xdg-desktop-portal
