cursor            #bbc3ff
cursor_text_color #232c61

foreground            #e4e1e9
background            #0d0e13
selection_foreground  #2d2f42
selection_background  #c4c5dd
url_color             #c4c5dd

#: black 000000 767676
color0  #040404
color8  #4c4c55
#: red cc0403 f2201f
color1  #ff4c63
color9  #ffe5e8
#: green 19cb00 23fd00
color2  #4ab870
color10 #b8e3c7
#: yellow cecb00 fffd00
color3  #83ae45
color11 #cadfad
#: blue 0d73cc 1a8fff
color4  #5569ff
color12 #eef0ff
#: magenta cb1ed1 fd28ff
color5  #e55ac3
color13 #fadef3
#: cyan 0dcdcd 14ffff
color6  #31abe4
color14 #b8e2f6
#: white dddddd ffffff
color7  #c7c5d0
color15 #e4e1e9

mark1_foreground #0c154b
mark1_background #dee0ff
mark2_foreground #181a2c
mark2_background #e0e1f9
mark3_foreground #2d1227
mark3_background #ffd7f1

active_tab_foreground #232c61
active_tab_background #bbc3ff
inactive_tab_foreground #dee0ff
inactive_tab_background #3a4379

active_border_color #bbc3ff
inactive_border_color #232c61
# bell_border_color #ff5a00