#!/bin/bash

gsettings set org.gnome.desktop.wm.keybindings activate-window-menu "['<Alt>space']"
gsettings set org.gnome.desktop.wm.keybindings always-on-top  "[]"
gsettings set org.gnome.desktop.wm.keybindings begin-move  "[]"
gsettings set org.gnome.desktop.wm.keybindings begin-resize  "[]"
gsettings set org.gnome.desktop.wm.keybindings close "['<Alt>F4']"
gsettings set org.gnome.desktop.wm.keybindings cycle-group "['<Alt>F6']"
gsettings set org.gnome.desktop.wm.keybindings cycle-group-backward "['<Shift><Alt>F6']"
gsettings set org.gnome.desktop.wm.keybindings cycle-panels "['<Control><Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings cycle-panels-backward "['<Shift><Control><Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings cycle-windows "['<Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward "['<Shift><Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings lower  "[]"
gsettings set org.gnome.desktop.wm.keybindings maximize  "[]"
gsettings set org.gnome.desktop.wm.keybindings maximize-horizontally  "[]"
gsettings set org.gnome.desktop.wm.keybindings maximize-vertically  "[]"
gsettings set org.gnome.desktop.wm.keybindings minimize  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-center  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-ne  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-nw  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-se  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-sw  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-down  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-left  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-right  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-up  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-e  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-n  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-s  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-w  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-11  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-12  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Control><Shift><Alt>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-last  "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Super><Shift>Page_Up', '<Super><Shift><Alt>Left', '<Control><Shift><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Super><Shift>Page_Down', '<Super><Shift><Alt>Right', '<Control><Shift><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Control><Shift><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings panel-main-menu  "[]"
gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog "['<Alt>F2']"
gsettings set org.gnome.desktop.wm.keybindings raise  "[]"
gsettings set org.gnome.desktop.wm.keybindings raise-or-lower  "[]"
gsettings set org.gnome.desktop.wm.keybindings set-spew-mark  "[]"
gsettings set org.gnome.desktop.wm.keybindings show-desktop  "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super>Tab', '<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Super>Tab', '<Shift><Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group "['<Super>Above_Tab', '<Alt>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group-backward "['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Super>space', 'XF86Keyboard']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift><Super>space', '<Shift>XF86Keyboard']"
gsettings set org.gnome.desktop.wm.keybindings switch-panels "['<Control><Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-panels-backward "['<Shift><Control><Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>7']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8  "['<Super>8']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9  "['<Super>9']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10  "['<Super>0']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-11  "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-12  "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Control><Alt>Down']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-last "['<Super>End']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>Page_Up', '<Super><Alt>Left', '<Control><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Page_Down', '<Super><Alt>Right', '<Control><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Control><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows  "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward  "[]"
gsettings set org.gnome.desktop.wm.keybindings toggle-above  "[]"
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen  "[]"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized  "[]"
gsettings set org.gnome.desktop.wm.keybindings toggle-on-all-workspaces  "[]"
gsettings set org.gnome.desktop.wm.keybindings unmaximize  "[]"
gsettings set org.gnome.mutter.keybindings cancel-input-capture "['<Super><Shift>Escape']"
gsettings set org.gnome.mutter.keybindings rotate-monitor "['XF86RotateWindows']"
gsettings set org.gnome.mutter.keybindings switch-monitor  "[]"
gsettings set org.gnome.mutter.keybindings toggle-tiled-left  "[]"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right  "[]"
gsettings set org.gnome.mutter.wayland.keybindings restore-shortcuts  "[]"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-1 "['<Primary><Alt>F1']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-10 "['<Primary><Alt>F10']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-11 "['<Primary><Alt>F11']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-12 "['<Primary><Alt>F12']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-2 "['<Primary><Alt>F2']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-3 "['<Primary><Alt>F3']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-4 "['<Primary><Alt>F4']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-5 "['<Primary><Alt>F5']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-6 "['<Primary><Alt>F6']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-7 "['<Primary><Alt>F7']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-8 "['<Primary><Alt>F8']"
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-9 "['<Primary><Alt>F9']"
gsettings set org.gnome.settings-daemon.plugins.media-keys battery-status "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys battery-status-static "['XF86Battery']"
gsettings set org.gnome.settings-daemon.plugins.media-keys calculator "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys calculator-static "['XF86Calculator']"
gsettings set org.gnome.settings-daemon.plugins.media-keys control-center "['<Super>p']"
gsettings set org.gnome.settings-daemon.plugins.media-keys control-center-static "['XF86Tools']"
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys decrease-text-size "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys eject "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys eject-static "['XF86Eject']"
gsettings set org.gnome.settings-daemon.plugins.media-keys email "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys email-static "['XF86Mail']"
gsettings set org.gnome.settings-daemon.plugins.media-keys help "['', '<Super>F1']"
gsettings set org.gnome.settings-daemon.plugins.media-keys hibernate "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys hibernate-static "['XF86Suspend', 'XF86Hibernate']"
gsettings set org.gnome.settings-daemon.plugins.media-keys home "['<Super>e']"
gsettings set org.gnome.settings-daemon.plugins.media-keys home-static "['XF86Explorer']"
gsettings set org.gnome.settings-daemon.plugins.media-keys increase-text-size "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys keyboard-brightness-down "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys keyboard-brightness-down-static "['XF86KbdBrightnessDown']"
gsettings set org.gnome.settings-daemon.plugins.media-keys keyboard-brightness-toggle "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys keyboard-brightness-toggle-static "['XF86KbdLightOnOff']"
gsettings set org.gnome.settings-daemon.plugins.media-keys keyboard-brightness-up "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys keyboard-brightness-up-static "['XF86KbdBrightnessUp']"
gsettings set org.gnome.settings-daemon.plugins.media-keys logout "['<Control><Alt>Delete']"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier  "[]"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier-zoom-in  "[]"
gsettings set org.gnome.settings-daemon.plugins.media-keys magnifier-zoom-out  "[]"
gsettings set org.gnome.settings-daemon.plugins.media-keys media "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys media-static "['XF86AudioMedia']"
gsettings set org.gnome.settings-daemon.plugins.media-keys mic-mute "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys mic-mute-static "['XF86AudioMicMute']"
gsettings set org.gnome.settings-daemon.plugins.media-keys next "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys next-static "['XF86AudioNext', '<Ctrl>XF86AudioNext']"
gsettings set org.gnome.settings-daemon.plugins.media-keys on-screen-keyboard "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys pause "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys pause-static "['XF86AudioPause']"
gsettings set org.gnome.settings-daemon.plugins.media-keys play "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys play-static "['XF86AudioPlay', '<Ctrl>XF86AudioPlay']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-forward "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-forward-static "['XF86AudioForward']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-random "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-random-static "['XF86AudioRandomPlay']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-repeat "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-repeat-static "['XF86AudioRepeat']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-rewind "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys playback-rewind-static "['XF86AudioRewind']"
gsettings set org.gnome.settings-daemon.plugins.media-keys power "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys power-static "['XF86PowerOff']"
gsettings set org.gnome.settings-daemon.plugins.media-keys previous "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys previous-static "['XF86AudioPrev', '<Ctrl>XF86AudioPrev']"
gsettings set org.gnome.settings-daemon.plugins.media-keys reboot "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys rfkill "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys rfkill-bluetooth "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys rfkill-bluetooth-static "['XF86Bluetooth']"
gsettings set org.gnome.settings-daemon.plugins.media-keys rfkill-static "['XF86WLAN', 'XF86UWB', 'XF86RFKill']"
gsettings set org.gnome.settings-daemon.plugins.media-keys rotate-video-lock "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys rotate-video-lock-static "['<Super>o', 'XF86RotationLockToggle']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-cycle "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-cycle-static "['XF86MonBrightnessCycle']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-down "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-down-static "['XF86MonBrightnessDown']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-up "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-up-static "['XF86MonBrightnessUp']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenreader "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "['<Super>l']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver-static "['XF86ScreenSaver']"
gsettings set org.gnome.settings-daemon.plugins.media-keys search "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys search-static "['XF86Search']"
gsettings set org.gnome.settings-daemon.plugins.media-keys shutdown "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys stop "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys stop-static "['XF86AudioStop']"
gsettings set org.gnome.settings-daemon.plugins.media-keys suspend "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys suspend-static "['XF86Sleep']"
gsettings set org.gnome.settings-daemon.plugins.media-keys toggle-contrast "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys touchpad-off "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys touchpad-off-static "['XF86TouchpadOff']"
gsettings set org.gnome.settings-daemon.plugins.media-keys touchpad-on "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys touchpad-on-static "['XF86TouchpadOn']"
gsettings set org.gnome.settings-daemon.plugins.media-keys touchpad-toggle "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys touchpad-toggle-static "['XF86TouchpadToggle', '<Ctrl><Super>XF86TouchpadToggle']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down-precise "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down-precise-static "['<Shift>XF86AudioLowerVolume', '<Ctrl><Shift>XF86AudioLowerVolume']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down-quiet "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down-quiet-static "['<Alt>XF86AudioLowerVolume', '<Alt><Ctrl>XF86AudioLowerVolume']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down-static "['XF86AudioLowerVolume', '<Ctrl>XF86AudioLowerVolume']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-mute "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-mute-quiet "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-mute-quiet-static "['<Alt>XF86AudioMute']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-mute-static "['XF86AudioMute']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-step 6
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up-precise "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up-precise-static "['<Shift>XF86AudioRaiseVolume', '<Ctrl><Shift>XF86AudioRaiseVolume']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up-quiet "['']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up-quiet-static "['<Alt>XF86AudioRaiseVolume', '<Alt><Ctrl>XF86AudioRaiseVolume']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up-static "['XF86AudioRaiseVolume', '<Ctrl>XF86AudioRaiseVolume']"
gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Super>w']"
gsettings set org.gnome.settings-daemon.plugins.media-keys www-static "['XF86WWW']"
gsettings set org.gnome.shell.keybindings focus-active-notification  "[]"
gsettings set org.gnome.shell.keybindings open-new-window-application-1 "['<Super><Control>1']"
gsettings set org.gnome.shell.keybindings open-new-window-application-2 "['<Super><Control>2']"
gsettings set org.gnome.shell.keybindings open-new-window-application-3 "['<Super><Control>3']"
gsettings set org.gnome.shell.keybindings open-new-window-application-4 "['<Super><Control>4']"
gsettings set org.gnome.shell.keybindings open-new-window-application-5 "['<Super><Control>5']"
gsettings set org.gnome.shell.keybindings open-new-window-application-6 "['<Super><Control>6']"
gsettings set org.gnome.shell.keybindings open-new-window-application-7 "['<Super><Control>7']"
gsettings set org.gnome.shell.keybindings open-new-window-application-8 "['<Super><Control>8']"
gsettings set org.gnome.shell.keybindings open-new-window-application-9 "['<Super><Control>9']"
gsettings set org.gnome.shell.keybindings screenshot "['<Shift>Print']"
gsettings set org.gnome.shell.keybindings screenshot-window "['<Alt>Print']"
gsettings set org.gnome.shell.keybindings shift-overview-down "['<Super><Alt>Down']"
gsettings set org.gnome.shell.keybindings shift-overview-up "['<Super><Alt>Up']"
gsettings set org.gnome.shell.keybindings show-screen-recording-ui "['<Ctrl><Shift><Alt>R']"
gsettings set org.gnome.shell.keybindings show-screenshot-ui "['Print']"
gsettings set org.gnome.shell.keybindings switch-to-application-1  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-2  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-3  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-4  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-5  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-6  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-7  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-8  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-9  "[]"
gsettings set org.gnome.shell.keybindings toggle-application-view "['<Super>a']"
gsettings set org.gnome.shell.keybindings toggle-message-tray "['<Super>n']"
gsettings set org.gnome.shell.keybindings toggle-overview  "[]"
gsettings set org.gnome.shell.keybindings toggle-quick-settings  "[]"
