$image = /home/deadbyte/dotfiles/files/Pictures/Wallpapers/pooki-red.jpeg

$background = rgba(1a120eff)

$blue = rgba(cbbeffff)

$blue_container = rgba(493e76ff)

$blue_source = rgba(455bffff)

$blue_value = rgba(455bffff)

$cyan = rgba(80d4d6ff)

$cyan_container = rgba(004f51ff)

$cyan_source = rgba(8be9fdff)

$cyan_value = rgba(8be9fdff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$green = rgba(b4d087ff)

$green_container = rgba(374d13ff)

$green_source = rgba(00ff40ff)

$green_value = rgba(00ff40ff)

$inverse_on_surface = rgba(382e2aff)

$inverse_primary = rgba(8d4e2bff)

$inverse_surface = rgba(f0dfd8ff)

$magenta = rgba(ffb2bfff)

$magenta_container = rgba(713340ff)

$magenta_source = rgba(ff4eb2ff)

$magenta_value = rgba(ff4eb2ff)

$on_background = rgba(f0dfd8ff)

$on_blue = rgba(33275eff)

$on_blue_container = rgba(e7deffff)

$on_cyan = rgba(003738ff)

$on_cyan_container = rgba(9cf1f2ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_green = rgba(223600ff)

$on_green_container = rgba(d0eda1ff)

$on_magenta = rgba(561d2bff)

$on_magenta_container = rgba(ffd9deff)

$on_orange = rgba(512400ff)

$on_orange_container = rgba(ffdbc7ff)

$on_primary = rgba(542103ff)

$on_primary_container = rgba(ffdbcbff)

$on_primary_fixed = rgba(341100ff)

$on_primary_fixed_variant = rgba(703716ff)

$on_red = rgba(561f0eff)

$on_red_container = rgba(ffdbd1ff)

$on_secondary = rgba(432a1eff)

$on_secondary_container = rgba(ffdbcbff)

$on_secondary_fixed = rgba(2c160bff)

$on_secondary_fixed_variant = rgba(5c4033ff)

$on_surface = rgba(f0dfd8ff)

$on_surface_variant = rgba(d7c2b9ff)

$on_tertiary = rgba(353107ff)

$on_tertiary_container = rgba(ece4aaff)

$on_tertiary_fixed = rgba(1f1c00ff)

$on_tertiary_fixed_variant = rgba(4c481cff)

$on_yellow = rgba(383100ff)

$on_yellow_container = rgba(f4e489ff)

$orange = rgba(ffb688ff)

$orange_container = rgba(6e380fff)

$orange_source = rgba(ff9019ff)

$orange_value = rgba(ff9019ff)

$outline = rgba(a08d85ff)

$outline_variant = rgba(52443dff)

$primary = rgba(ffb692ff)

$primary_container = rgba(703716ff)

$primary_fixed = rgba(ffdbcbff)

$primary_fixed_dim = rgba(ffb692ff)

$red = rgba(ffb59fff)

$red_container = rgba(723522ff)

$red_source = rgba(ff2b2bff)

$red_value = rgba(ff2b2bff)

$scrim = rgba(000000ff)

$secondary = rgba(e6beacff)

$secondary_container = rgba(5c4033ff)

$secondary_fixed = rgba(ffdbcbff)

$secondary_fixed_dim = rgba(e6beacff)

$shadow = rgba(000000ff)

$source_color = rgba(392013ff)

$surface = rgba(1a120eff)

$surface_bright = rgba(423732ff)

$surface_container = rgba(271e19ff)

$surface_container_high = rgba(322823ff)

$surface_container_highest = rgba(3d332eff)

$surface_container_low = rgba(221a16ff)

$surface_container_lowest = rgba(140c09ff)

$surface_dim = rgba(1a120eff)

$surface_tint = rgba(ffb692ff)

$surface_variant = rgba(52443dff)

$tertiary = rgba(d0c890ff)

$tertiary_container = rgba(4c481cff)

$tertiary_fixed = rgba(ece4aaff)

$tertiary_fixed_dim = rgba(d0c890ff)

$yellow = rgba(d7c770ff)

$yellow_container = rgba(514700ff)

$yellow_source = rgba(f0ff4eff)

$yellow_value = rgba(f0ff4eff)
