$image = /disks/archives/Photos/Backgrounds/catppuccin.png

$background = rgba(131318ff)

$blue = rgba(bbc3ffff)

$blue_container = rgba(3a4279ff)

$blue_source = rgba(455bffff)

$blue_value = rgba(455bffff)

$cyan = rgba(8bd0f0ff)

$cyan_container = rgba(004d64ff)

$cyan_source = rgba(8be9fdff)

$cyan_value = rgba(8be9fdff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$green = rgba(93d5aaff)

$green_container = rgba(095131ff)

$green_source = rgba(00ff40ff)

$green_value = rgba(00ff40ff)

$inverse_on_surface = rgba(303036ff)

$inverse_primary = rgba(525a92ff)

$inverse_surface = rgba(e4e1e9ff)

$magenta = rgba(f3b2e3ff)

$magenta_container = rgba(67355eff)

$magenta_source = rgba(ff4eb2ff)

$magenta_value = rgba(ff4eb2ff)

$on_background = rgba(e4e1e9ff)

$on_blue = rgba(232c61ff)

$on_blue_container = rgba(dfe0ffff)

$on_cyan = rgba(003546ff)

$on_cyan_container = rgba(bee9ffff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_green = rgba(003920ff)

$on_green_container = rgba(aef2c5ff)

$on_magenta = rgba(4d1f47ff)

$on_magenta_container = rgba(ffd7f2ff)

$on_orange = rgba(542105ff)

$on_orange_container = rgba(ffdbccff)

$on_primary = rgba(232c61ff)

$on_primary_container = rgba(dee0ffff)

$on_primary_fixed = rgba(0c154bff)

$on_primary_fixed_variant = rgba(3a4379ff)

$on_red = rgba(561d28ff)

$on_red_container = rgba(ffd9ddff)

$on_secondary = rgba(2d2f42ff)

$on_secondary_container = rgba(e0e1f9ff)

$on_secondary_fixed = rgba(181a2cff)

$on_secondary_fixed_variant = rgba(434559ff)

$on_surface = rgba(e4e1e9ff)

$on_surface_variant = rgba(c7c5d0ff)

$on_tertiary = rgba(44263dff)

$on_tertiary_container = rgba(ffd7f1ff)

$on_tertiary_fixed = rgba(2d1227ff)

$on_tertiary_fixed_variant = rgba(5d3c54ff)

$on_yellow = rgba(203600ff)

$on_yellow_container = rgba(ceeda2ff)

$orange = rgba(ffb694ff)

$orange_container = rgba(713719ff)

$orange_source = rgba(ff9019ff)

$orange_value = rgba(ff9019ff)

$outline = rgba(90909aff)

$outline_variant = rgba(46464fff)

$primary = rgba(bbc3ffff)

$primary_container = rgba(3a4379ff)

$primary_fixed = rgba(dee0ffff)

$primary_fixed_dim = rgba(bbc3ffff)

$red = rgba(ffb2bcff)

$red_container = rgba(72333eff)

$red_source = rgba(ff2b2bff)

$red_value = rgba(ff2b2bff)

$scrim = rgba(000000ff)

$secondary = rgba(c4c5ddff)

$secondary_container = rgba(434559ff)

$secondary_fixed = rgba(e0e1f9ff)

$secondary_fixed_dim = rgba(c4c5ddff)

$shadow = rgba(000000ff)

$source_color = rgba(9aa2dcff)

$surface = rgba(131318ff)

$surface_bright = rgba(39393fff)

$surface_container = rgba(1f1f25ff)

$surface_container_high = rgba(29292fff)

$surface_container_highest = rgba(34343aff)

$surface_container_low = rgba(1b1b21ff)

$surface_container_lowest = rgba(0d0e13ff)

$surface_dim = rgba(131318ff)

$surface_tint = rgba(bbc3ffff)

$surface_variant = rgba(46464fff)

$tertiary = rgba(e6bad7ff)

$tertiary_container = rgba(5d3c54ff)

$tertiary_fixed = rgba(ffd7f1ff)

$tertiary_fixed_dim = rgba(e6bad7ff)

$yellow = rgba(b3d089ff)

$yellow_container = rgba(364e15ff)

$yellow_source = rgba(f0ff4eff)

$yellow_value = rgba(f0ff4eff)
