exec-once = hyprctl dispatch workspace 1

# Ambxst
source = ~/.local/share/ambxst/hyprland.conf

# OVERRIDES
# Down here you can write or source anything that you want to override from Ambxst's settings.

source = ~/.config/hypr/hardware.conf
source = ~/.config/hypr/workspaces.conf

exec = gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
