source = ~/.config/hypr/colors.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = $image   # Change this to your wallpaper path
    color = $background
    blur_passes = 2 # 0 disables blurring
}

# TIME (Clock style)
label {
    monitor =
    text = $TIME
    color = $primary
    font_size = 90
    font_family = AtkynsonMono NFP Bold
    position = 0, 80
    halign = center
    valign = center
}

# USER GREETING
label {
    monitor =
    text = Hi there, $USER
    color = $primary
    font_size = 20
    font_family = AtkynsonMono NFP
    position = 0, 0
    halign = center
    valign = center
}

# INPUT FIELD (The "Pill" design)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $on_secondary_container
    inner_color = $secondary_container
    font_color = $on_secondary_container
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 8 # Matching your Waybar border-radius
    check_color = $blue
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -80
    halign = center
    valign = center
}