'$schema' = 'https://starship.rs/config-schema.json'
add_newline = false

# Left side
format = '''$time$username$directory $character'''

# Right side
right_format = '''$cmd_duration  $nodejs $deno $python $c $cpp $golang $rust $java $dotnet $zig  $git_branch$git_state$git_status $git_metrics'''


##########################################################
######################### Prompt #########################
##########################################################

[os]
format = '$symbol'
disabled = true

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇'
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
format = ' in [$path]($style)'
truncation_length = 4
truncation_symbol = '.../'
style = 'bold fg:bright-blue'
truncate_to_repo=true

[username]
format = '[$user]($style)'
style_root = 'bold bright-magenta'
style_user = 'bold bright-yellow'
show_always = true

[time]
format = '[$time](bright-black)'
time_format = '%H:%M '
disabled = true

[character]
success_symbol = '[❯](bright-green)'
error_symbol = '[❯](bright-red)'

[cmd_duration]
disabled = false
min_time = 1000
show_milliseconds = true
format = '[${duration}](${style})'
style = "bold white"



##########################################################
######################## Languages #######################
##########################################################

[aws]
# TODO: Implement fully
disabled = true
symbol = ""

[bun]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[Bun ${version}\]]($style)'
style = 'white'

[c]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[C ${version}\]]($style)'
style = 'blue'

[cmake]
# TODO: Implement fully
disabled = true
symbol = ""

[deno]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[Deno ${version}\]]($style)'
style = 'white'

[docker_context]
# TODO: Implement fully
disabled = true

[dotnet]
disabled = false
detect_extensions = []
symbol = ""
format = '[\[.NET ${version}\]]($style)'
style = 'blue'
heuristic = true

[nodejs]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[NodeJS ${version}\]]($style)'
style = 'green'

[python]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[Python ${version}\]]($style)'
style = 'yellow'

[java]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[Java ${version}\]]($style)'
style = 'red'

[rust]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[Rust ${version}\]]($style)'
style = 'red'

[cpp]
disabled = false
detect_extensions = []
symbol = '󰙲'
format = '[\[C++ ${version}\]]($style)'
style = 'blue'

[golang]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[Go ${version}\]]($style)'
style = 'bright-cyan'

[zig]
disabled = false
detect_extensions = []
symbol = ''
format = '[\[Zig ${version}\]]($style)'
style = 'yellow'


##########################################################
########################### Git ##########################
##########################################################

[git_branch]
format = '[$symbol $branch]($style) '
symbol = ''
style = "white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[CHERRY PICKING](#f38ba8)'
merge = '[MERGE](cyan)'
rebase = '[REBASE](cyan)'
revert = '[REVERT](yellow)'

[git_status]
format = '$ahead_behind$all_status'
renamed = '[$count»](#bright-cyan)'
conflicted = '[C](bright-magenta)'
up_to_date = ''
untracked = '[$count?](bright-white)'
stashed = '[$count$](bright-blue)'
modified = '[$count!](bright-yellow)'
staged = '[$count+](bright-green)'
deleted = '[$count*](bright-red)'

ahead = '${count}⇡'
diverged = '⇕${ahead_count}⇡${behind_count}⇣'
behind = '${count}⇣'

[git_metrics]
disabled = false
only_nonzero_diffs = false
added_style = 'bold bright-green'
deleted_style = 'bold bright-red'
format = '[++$added]($added_style)|[--$deleted]($deleted_style) '
